### ISSUE TITLE
react admin v3 alpha has breaking changes any plans to update ?

### ISSUE THREAD

**Issue by MohammedFaragallah** [josx/ra-data-feathers#110]
for now i think restClient has some issues with InputReference
authClient has issues with logging out

**Comment by josx** [comment]
Would be great to support it, and i think we need to.
Are there already any information about the breaking changes?
Do you now when it would become the stable version?

**Comment by MohammedFaragallah** [comment]
no i don't think there is an announced release date

**Comment by josx** [comment]
Please if you are considering using agaisnt alpha v3 and can do tests, a provisional PR for that we can add a new branch with that in the meantime. What do you think?

**Comment by MohammedFaragallah** [comment]
Right now the changes i made was only workaround some strange behavior with react-admin i don't think that's what they mean to do
But I'm updating daily once anything seems stable I'll submit a PR for sure 😊👍
I'm having a question though why didn't you return a promise resolve from logout case like the others

**Comment by josx** [comment]
Ok, will be waiting for that PR. ;)

I am returning a promise resolve because:
- I have used as template auth in documentation and an example of data provider. (check [auth](https://marmelab.com/react-admin/Authorization.html))
- Anyways I thought that react-admin will need that resolve to continue the code execution.

**Comment by alex-all3dp** [comment]
@MohammedFaragallah @josx How is that v3 support coming along? :)

**Comment by josx** [comment]
I dont have any production running react-admin 3.x app yet. But I think It would work, because there are no breaking changes for authrProvider and dataProvider. 

I have read https://github.com/marmelab/react-admin/blob/master/UPGRADE.md
And upgrade dont apply something We have in the our code.

Anyway please if you can test it against.

**Comment by MohammedFaragallah** [comment]
Sorry I forgot about this, I have a project running with feathers 4/react-admin 3 if you are facing any issues please let me know, but as josx mentioned you should be fine there were no breaking changes.

**Comment by AshotN** [comment]
> Sorry I forgot about this, I have a project running with feathers 4/react-admin 3 if you are facing any issues please let me know, but as josx mentioned you should be fine there were no breaking changes.

I just went through a similar struggle 
This is what you are probably missing

https://docs.feathersjs.com/api/authentication/client.html

**Comment by josx** [comment]
But featherjs client is in [package.json as peerdependency](https://github.com/josx/ra-data-feathers/blob/master/package.json#L48) 

But depending in which `npm` version you are running, will or wont install peerdeps as default.( [npm doc](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependencies) )

Another idea is to add something like [check-peer-dependencies](https://github.com/christopherthielen/check-peer-dependencies) or similar.
