### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by soullivaneuh** [josx/ra-data-feathers#153]
Providing typescript support to the library will be a real addition for IDE code completion and human error avoiding.

Currently, if I import it on a `.tsx` file:

```typescript
```

I have the following error:

```typescript
Could not find a declaration file for module 'ra-data-feathers'.
'node_modules/ra-data-feathers/lib/index.js' implicitly has an 'any' type.'
Try `npm i --save-dev @types/ra-data-feathers` if it exists or add a new declaration (.d.ts) file containing `declare module 'ra-data-feathers';
```

I can of course declare the module manually, but I will not have any IDE completion for this dependency.

Regards

**Comment by josx** [comment]
I dont use typescript. 
what do you propose? Can you make a PR?

**Comment by soullivaneuh** [comment]
The purpose is to have strict typing and IDE completion.

I may, but I unfortunately not the time for that currently.

I propose to let the issue opened if any other interested people want to take care of this. :+1:

**Comment by josx** [comment]
Ok, I will

**Comment by berviantoleo** [comment]
Hi, may I try to take care of this? I also guess to use rollup when using Typescript, is it okay?

**Comment by josx** [comment]
Right now we are using just a makefile for building, installing.
Check #93 (but if we use rollup or anything else I want to also migrate those tasks to it)

Right now in this project We support react admin 2 and 3. Is it worth it to loose  versions support because typescript (ide and strict typing)?

**Comment by berviantoleo** [comment]
```
Right now we are using just a makefile for building, installing.
Check #93 (but if we use rollup or anything else I want to also migrate those tasks to it)
```

I think for that, better to move the task to `package.json` instead of `makefile`, so it will not limit to Linux.

```
Right now in this project We support react admin 2 and 3. Is it worth it to loose versions support because typescript (ide and strict typing)?
```
This breaking changes happened when I use the whole script as typescript and use rollup to build. But, if they need the type definition only, I think, yes it can be provided too. Let me try take a look this [article](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html). Seems it will allowed to generate the type definition from current library.

About worth, I think it's not really worth for now. But maybe just make this a long plan? Until they no longer update react admin 2?

**Comment by berviantoleo** [comment]
I create alternatives without change all source code to typescript at #154.

How about this?

**Comment by josx** [comment]
Great! merged
