### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by jamesholcomb** [josx/ra-data-feathers#161]
ra-data-feathers@2.9.0

```js
import feathers from "@feathersjs/feathers"
import feathersRestClient from "@feathersjs/rest-client"
import auth from "@feathersjs/authentication-client"
import { restClient, authClient } from "ra-data-feathers"

const client = feathers()
  .configure(feathersRestClient("http://localhost:3030").fetch(window.fetch))
  .configure(
    auth({
      storage: window.localStorage,
    })
  )
const restClientOptions = {
  id: "_id", // In this example, the database uses '_id' rather than 'id'
  usePatch: true, // Use PATCH instead of PUT for updates
}

const authClientOptions = {
  authenticate: {
    // Options included in calls to Feathers client.authenticate
    strategy: "jwt", // The authentication strategy Feathers should use
  },
  storageKey: "feathers-jwt",
  logoutOnForbidden: false,
  permissionsField: "role", // Use the 'userroles' field on the JWT as the users role
  redirectTo: "/login", // Our example login form might be at '/signin', redirect here if AUTH_CHECK fails
}

const dataProvider = restClient(client, restClientOptions)
```

The last line generates an error:
```
Argument of type '{ id: string; usePatch: boolean; }' is not assignable to parameter of type '{ usePatch?: boolean | undefined; customQueryOperators?: string[] | undefined; useMulti?: boolean | undefined; id?: string | undefined; } & { [Key: string]: { id: string; }; }'.
  Type '{ id: string; usePatch: boolean; }' is not assignable to type '{ [Key: string]: { id: string; }; }'.
    Property 'id' is incompatible with index signature.
      Type 'string' is not assignable to type '{ id: string; }'.
```

**Comment by josx** [comment]
So sorry about that. It seems to be an error on `@params`
To checkit out here in ts playground: [code](https://www.typescriptlang.org/play?filetype=js&useJavaScript=truee=4#code/PQKhFgCgAIWgBADgQwE7ILbQN7araaAVwGcBTABWQBcBjACwH4AuaAIwHsOAbM5AOwA00fHGi1S1DhgCKRMqgCeAeUQKaHVCRbQS1VAEt+AcwDaAXWGjCpMgFki3agZ2cefISJhiDAEx16hibQAL7WAGQ4pgDSZIqsgUbG5qzYfgn6SSFh3qHQHIjOHPwkosBQtMV60MjQALzQABQFRSUAlPUAfDj4hNCoZNREqPz5hQZVUDlQyI3YXoTp0ABEAPp+y4K9tg5OBqwAZsjc5FswxORUdPSs+vJW5xJ60nIKKmroUlqspsvLllMoG0ANxQKBAA)

The problem is  `& {[Key: string]: {id: string}}`, need to be optional (in words optional any key string with value object with id prop with type string value)
I dont know about types in typescript, can you help us @berviantoleo

**Comment by berviantoleo** [comment]
`The problem is & {[Key: string]: {id: string}}, need to be optional (in words optional any key string with value object with id prop with type string value)
I dont know about types in typescript, can you help us @berviantoleo`

Yes, you're right, I think I am wrong about that, need to make that optional. I will check to fix that.

**Comment by berviantoleo** [comment]
Previously I want to check the `"resource": {id: "_id"}` things, but seems I am wrong set it to required. I will send PR about that.

**Comment by josx** [comment]
BTW Can we add some tests for checking types to avoid this kind of bugs in the future

**Comment by berviantoleo** [comment]
> 
> 
> BTW Can we add some tests for checking types to avoid this kind of bugs in the future

Yes, I think can. But, the testing need use Typescript too. I will try to add some cases.

**Comment by josx** [comment]
@jamesholcomb  Please now you can try newest version [v2.9.1](https://www.npmjs.com/package/ra-data-feathers/v/2.9.1)

**Comment by jamesholcomb** [comment]
Works 👍
