### ISSUE TITLE
Investigate adding ability to build/test easily in Windows

### ISSUE THREAD

**Issue by nicholasnelson** [josx/ra-data-feathers#93]
I recently discovered it is not particularly easy to work on this project in Windows, due to the reliance on the Makefile to build the project.

It may be worth investigating the use of a platform independent alternative to Make. Grunt or Gulp would likely fill this need.

@josx, would you have any objection to a PR replacing the Makefile with one of the above options? I have some familiarity with both Grunt and Gulp, and don't have a preference for one over the other.

If the Makefile is needed for other things (i.e. CI), the Makefile could be updated to just call Grunt/Gulp task to avoid duplicating configuration of build steps.

**Comment by josx** [comment]
So sorry I dont use Windows, I know that you can use http://www.msys2.org/ or http://gnuwin32.sourceforge.net/.

But i think would be better to make the life easier for windows users ;)

Right We are using make just for two tasks:

```
clean: ## clean lib dir
	rm -rf lib

build: ## compile ES6 files to JS
	@NODE_ENV=production ./node_modules/.bin/babel ./src -d lib --ignore '*.spec.js'
```

So If you come up with gulp tasks for them and integrate in package.json would be a step forward.
Please do it

**Comment by josx** [comment]
Maybe it is clever just to add clean and build directly into package.json (just two onliners)

**Comment by berviantoleo** [comment]
> 
> 
> Maybe it is clever just to add clean and build directly into package.json (just two oneliners)

Yes, we can move the command to package.json, but for compatibility to Windows.

* The build command will need [cross-env](https://www.npmjs.com/package/cross-env) package, so it will support environment variable to cross Linux & Windows.
* For the clean command, I think will need [shx](https://www.npmjs.com/package/shx), since what I know current Windows not have `rm` command.

That is my suggestion in case we really need to move the command to `package.json`

**Comment by josx** [comment]
Sounds good to me. Please if you can make a PR with that.
